---
- hosts: default
  vars:
    rvm1_rubies:
      - 'ruby-2.2.3'
    project_root: /var/www/house_cup
    repo_url: https://github.com/Gradery/house-cup.git
    rails_environment: production
    url: hc.gradery.com
    db: 
      host: 
      name: 
      port: 5432
      pool: 25
      username: 
      password: 
    secret_key_base: 
    email:
      host: 
      port: 587
      username: 
      password: 
      domain: 
    redis_url: 
    fog:
      aws_access_key: 
      aws_secret_key: 
      bucket: 
      wkhtmltopdf_binary: /usr/local/bin/wkhtmltopdf
    sidekiq:
      concurrency: 5
  remote_user: vagrant
  become: yes
  roles:
     - rvm
  tasks:
    - name: Install git
      apt:
        name: git
        state: latest
    - name: Install build-essential
      apt:
        name: build-essential
        state: latest
    - name: Install libgmp3-dev
      apt:
        name: libgmp3-dev
        state: latest
    - name: Install libpq-dev
      apt:
        name: libpq-dev
        state: latest
    - name: Install ImageMagick
      apt:
        name: imagemagick
        state: latest
    - name: Install libmagickwand-dev
      apt:
        name: libmagickwand-dev
        state: latest
    - name: Install Supervisord
      apt:
        name: supervisor
        state: latest
    - name: Install Bundler
      gem:
        name: bundler
        state: latest
    - name: Clone git repo
      git:
        accept_hostkey: yes
        dest: "{{project_root}}"
        force: yes
        repo: "{{repo_url}}"
    - name: Bundle Install
      shell: "bundle install --with={{rails_environment}}"
      args:
        chdir: "{{project_root}}"
    - name: Upload database file
      template:
        src: config/database.yml.j2
        dest: "{{project_root}}/config/database.yml"
    - name: Upload secrets file
      template:
        src: config/secrets.yml.j2
        dest: "{{project_root}}/config/secrets.yml"
    - name: Upload environments file
      template:
        src: "config/environments/{{rails_environment}}.rb.j2"
        dest: "{{project_root}}/config/environments/{{rails_environment}}.rb"
    - name: Upload fog initializer file
      template:
        src: "config/initializers/fog.rb.j2"
        dest: "{{project_root}}/config/initializers/fog.rb"
    - name: Upload Sidekiq config file
      template:
        src: "config/sidekiq.yml.j2"
        dest: "{{project_root}}/config/sidekiq.yml"
    - name: Upload Supervisord config file
      template:
        src: "config/supervisord.conf.j2"
        dest: "/etc/supervisor/conf.d/house_cup.conf"
    - name: Make PIDs folder
      file: 
        path: "{{project_root}}/tmp/pids"
        state: directory
    - name: Restart Supervisord
      service:
        name: supervisor
        enabled: yes
        state: restarted