---
- hosts: default
  vars:
    rvm1_rubies:
      - 'ruby-2.2.3'
    project_root: /var/www/house_cup
    repo_url: https://github.com/Gradery/house-cup.git
    rails_environment: production
    url: hc.gradery.com
    db: 
      host: 
      name: 
      port: 5432
      pool: 25
      username: 
      password: 
    secret_key_base: 
    email:
      host: 
      port: 587
      username: 
      password: 
      domain: 
    redis_url: redis://
    fog:
      aws_access_key: 
      aws_secret_key: 
      bucket: 
      wkhtmltopdf_binary: /usr/local/bin/wkhtmltopdf
  remote_user: vagrant
  become: yes
  roles:
     - rvm
     - nginx-passenger
  tasks:
    - name: Install git
      apt:
        name: git
        state: latest
    - name: Install build-essential
      apt:
        name: build-essential
        state: latest
    - name: Install libgmp3-dev
      apt:
        name: libgmp3-dev
        state: latest
    - name: Install libpq-dev
      apt:
        name: libpq-dev
        state: latest
    - name: Install ImageMagick
      apt:
        name: imagemagick
        state: latest
    - name: Install libmagickwand-dev
      apt:
        name: libmagickwand-dev
        state: latest
    - name: Install Bundler
      shell: gem install bundler
    - name: Clone git repo
      git:
        accept_hostkey: yes
        dest: "{{project_root}}"
        force: yes
        repo: "{{repo_url}}"
    - name: Bundle Install
      shell: "bundle install --with={{rails_environment}}"
      args:
        chdir: "{{project_root}}"
    - name: Upload database file
      template:
        src: config/database.yml.j2
        dest: "{{project_root}}/config/database.yml"
    - name: Upload secrets file
      template:
        src: config/secrets.yml.j2
        dest: "{{project_root}}/config/secrets.yml"
    - name: Upload environments file
      template:
        src: "config/environments/{{rails_environment}}.rb.j2"
        dest: "{{project_root}}/config/environments/{{rails_environment}}.rb"
    - name: Upload fog initializer file
      template:
        src: "config/initializers/fog.rb.j2"
        dest: "{{project_root}}/config/initializers/fog.rb"
    - name: Upload Nginx main config
      template:
        src: "config/nginx/nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        force: yes
    - name: remove default site
      file:
        path: /etc/nginx/sites-available/default
        state: absent
    - name: remove default site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Upload project Nginx config
      template:
        src: "config/nginx/site.conf.j2"
        dest: "/etc/nginx/sites-enabled/house_cup.conf"
        force: yes
      notify:
      - nginx restart
    - name: Precompile assets
      shell: "RAILS_ENV={{rails_environment}} rake assets:precompile"
      args:
        chdir: "{{project_root}}"